mqtt:
 server: tcp://mqtt:1883
 client_id: mqtt2prometheus.zigbee
 topic_path: zigbee2mqtt/#
 device_id_regex: "[^\\/]+\\/(?P<deviceid>[^\\/]+)(.*)?"
 qos: 0
cache:
 timeout: 24h
json_parsing:
 separator: .

metrics:
 - prom_name: sensor_current
   mqtt_name: current
   help: current
   type: gauge

 - prom_name: sensor_voltage
   mqtt_name: voltage
   help: voltage
   type: gauge

 - prom_name: sensor_energy
   mqtt_name: energy
   help: energy
   type: gauge

 - prom_name: sensor_zigbee_linkquality
   mqtt_name: linkquality
   help: linkquality
   type: gauge
